version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recicleai-api
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./waste_collection.db
      - SECRET_KEY=${SECRET_KEY:-your_secret_key_here}
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - APP_ENV=production
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
